[package]
name = "keel"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Data model description engine: models and relations only"
readme = "../../README.md"

[lib]
path = "src/lib.rs"

[dependencies]
keel-macro = { workspace = true }
rusqlite = { workspace = true }
