[package]
name = "keel"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = ["perish"]
description = "Data model description engine: models and relations only"
readme = "../../README.md"

[lib]
path = "src/lib.rs"

[features]
default = ["http"]
http = ["dep:axum"]
pg = ["sqlx/postgres"]

[dependencies]
axum = { workspace = true, optional = true }
getrandom = { workspace = true }
keel-macro = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }

[dev-dependencies]
http-body-util = { workspace = true }
tower = { workspace = true }

[[test]]
name = "cap"
path = "tests/cap/main.rs"

[[test]]
name = "route"
path = "tests/route/main.rs"

[[test]]
name = "query"
path = "tests/query/main.rs"

[[test]]
name = "data"
path = "tests/data/main.rs"

[[test]]
name = "bond"
path = "tests/bond/main.rs"

[[test]]
name = "pulse"
path = "tests/pulse/main.rs"

[[test]]
name = "estate"
path = "tests/estate/main.rs"
