[workspace]
resolver = "3"
members = ["crates/keel", "crates/macro"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://git.perish.top/PerishLab/keel"

[workspace.dependencies]
keel = { path = "crates/keel" }
keel-macro = { path = "crates/macro" }
proc-macro2 = "1"
quote = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
syn = { version = "2", features = ["full"] }
